
SRC_ROOT=..
include z:/NBU_BUILD/freemason/4/main

MODULE_NAME=strings

PRODUCT=lib

#------------------------------------

include $(MK)/defs

#------------------------------------

define CC_PP_DEFS.common
endef

define CC_INCLUDE_DIRS.common
endef

define CC_SRC_FILES.common
	strings.cpp
endef

#------------------------------------

include $(MK)/rules
