
SRC_ROOT=..
include z:/NBU_BUILD/freemason/4/main

MODULE_NAME=test1

PRODUCT=prog

#------------------------------------

include $(MK)/defs

#------------------------------------

define CC_PP_DEFS.common
endef

define CC_INCLUDE_DIRS.common
	..
endef

define CC_SRC_FILES.common
	test1.cpp
endef

#------------------------------------

include $(MK)/rules
